import type { LabelAndEmoji } from "@/types"

const countries: LabelAndEmoji[] = [
  { label: "Afghanistan", emoji: "🇦🇫" },
  { label: "Albania", emoji: "🇦🇱" },
  { label: "Algeria", emoji: "🇩🇿" },
  { label: "Andorra", emoji: "🇦🇩" },
  { label: "Angola", emoji: "🇦🇴" },
  { label: "Antigua and Barbuda", emoji: "🇦🇬" },
  { label: "Argentina", emoji: "🇦🇷" },
  { label: "Armenia", emoji: "🇦🇲" },
  { label: "Australia", emoji: "🇦🇺" },
  { label: "Austria", emoji: "🇦🇹" },
  { label: "Azerbaijan", emoji: "🇦🇿" },
  { label: "Bahamas", emoji: "🇧🇸" },
  { label: "Bahrain", emoji: "🇧🇭" },
  { label: "Bangladesh", emoji: "🇧🇩" },
  { label: "Barbados", emoji: "🇧🇧" },
  { label: "Belarus", emoji: "🇧🇾" },
  { label: "Belgium", emoji: "🇧🇪" },
  { label: "Belize", emoji: "🇧🇿" },
  { label: "Benin", emoji: "🇧🇯" },
  { label: "Bhutan", emoji: "🇧🇹" },
  { label: "Bolivia", emoji: "🇧🇴" },
  { label: "Bosnia and Herzegovina", emoji: "🇧🇦" },
  { label: "Botswana", emoji: "🇧🇼" },
  { label: "Brazil", emoji: "🇧🇷" },
  { label: "Brunei", emoji: "🇧🇳" },
  { label: "Bulgaria", emoji: "🇧🇬" },
  { label: "Burkina Faso", emoji: "🇧🇫" },
  { label: "Burundi", emoji: "🇧🇮" },
  { label: "Cambodia", emoji: "🇰🇭" },
  { label: "Cameroon", emoji: "🇨🇲" },
  { label: "Canada", emoji: "🇨🇦" },
  { label: "Cape Verde", emoji: "🇨🇻" },
  { label: "Central African Republic", emoji: "🇨🇫" },
  { label: "Chad", emoji: "🇹🇩" },
  { label: "Chile", emoji: "🇨🇱" },
  { label: "China", emoji: "🇨🇳" },
  { label: "Colombia", emoji: "🇨🇴" },
  { label: "Comoros", emoji: "🇰🇲" },
  { label: "Congo (Brazzaville)", emoji: "🇨🇬" },
  { label: "Congo (Kinshasa)", emoji: "🇨🇩" },
  { label: "Costa Rica", emoji: "🇨🇷" },
  { label: "Croatia", emoji: "🇭🇷" },
  { label: "Cuba", emoji: "🇨🇺" },
  { label: "Cyprus", emoji: "🇨🇾" },
  { label: "Czech Republic", emoji: "🇨🇿" },
  { label: "Denmark", emoji: "🇩🇰" },
  { label: "Djibouti", emoji: "🇩🇯" },
  { label: "Dominica", emoji: "🇩🇲" },
  { label: "Dominican Republic", emoji: "🇩🇴" },
  { label: "Ecuador", emoji: "🇪🇨" },
  { label: "Egypt", emoji: "🇪🇬" },
  { label: "El Salvador", emoji: "🇸🇻" },
  { label: "Equatorial Guinea", emoji: "🇬🇶" },
  { label: "Eritrea", emoji: "🇪🇷" },
  { label: "Estonia", emoji: "🇪🇪" },
  { label: "Eswatini", emoji: "🇸🇿" },
  { label: "Ethiopia", emoji: "🇪🇹" },
  { label: "Fiji", emoji: "🇫🇯" },
  { label: "Finland", emoji: "🇫🇮" },
  { label: "France", emoji: "🇫🇷" },
  { label: "Gabon", emoji: "🇬🇦" },
  { label: "Gambia", emoji: "🇬🇲" },
  { label: "Georgia", emoji: "🇬🇪" },
  { label: "Germany", emoji: "🇩🇪" },
  { label: "Ghana", emoji: "🇬🇭" },
  { label: "Greece", emoji: "🇬🇷" },
  { label: "Grenada", emoji: "🇬🇩" },
  { label: "Guatemala", emoji: "🇬🇹" },
  { label: "Guinea", emoji: "🇬🇳" },
  { label: "Guinea-Bissau", emoji: "🇬🇼" },
  { label: "Guyana", emoji: "🇬🇾" },
  { label: "Haiti", emoji: "🇭🇹" },
  { label: "Honduras", emoji: "🇭🇳" },
  { label: "Hungary", emoji: "🇭🇺" },
  { label: "Iceland", emoji: "🇮🇸" },
  { label: "India", emoji: "🇮🇳" },
  { label: "Indonesia", emoji: "🇮🇩" },
  { label: "Iran", emoji: "🇮🇷" },
  { label: "Iraq", emoji: "🇮🇶" },
  { label: "Ireland", emoji: "🇮🇪" },
  { label: "Israel", emoji: "🇮🇱" },
  { label: "Italy", emoji: "🇮🇹" },
  { label: "Jamaica", emoji: "🇯🇲" },
  { label: "Japan", emoji: "🇯🇵" },
  { label: "Jordan", emoji: "🇯🇴" },
  { label: "Kazakhstan", emoji: "🇰🇿" },
  { label: "Kenya", emoji: "🇰🇪" },
  { label: "Kiribati", emoji: "🇰🇮" },
  { label: "Kuwait", emoji: "🇰🇼" },
  { label: "Kyrgyzstan", emoji: "🇰🇬" },
  { label: "Laos", emoji: "🇱🇦" },
  { label: "Latvia", emoji: "🇱🇻" },
  { label: "Lebanon", emoji: "🇱🇧" },
  { label: "Lesotho", emoji: "🇱🇸" },
  { label: "Liberia", emoji: "🇱🇷" },
  { label: "Libya", emoji: "🇱🇾" },
  { label: "Liechtenstein", emoji: "🇱🇮" },
  { label: "Lithuania", emoji: "🇱🇹" },
  { label: "Luxembourg", emoji: "🇱🇺" },
  { label: "Madagascar", emoji: "🇲🇬" },
  { label: "Malawi", emoji: "🇲🇼" },
  { label: "Malaysia", emoji: "🇲🇾" },
  { label: "Maldives", emoji: "🇲🇻" },
  { label: "Mali", emoji: "🇲🇱" },
  { label: "Malta", emoji: "🇲🇹" },
  { label: "Marshall Islands", emoji: "🇲🇭" },
  { label: "Mauritania", emoji: "🇲🇷" },
  { label: "Mauritius", emoji: "🇲🇺" },
  { label: "Mexico", emoji: "🇲🇽" },
  { label: "Micronesia", emoji: "🇫🇲" },
  { label: "Moldova", emoji: "🇲🇩" },
  { label: "Monaco", emoji: "🇲🇨" },
  { label: "Mongolia", emoji: "🇲🇳" },
  { label: "Montenegro", emoji: "🇲🇪" },
  { label: "Morocco", emoji: "🇲🇦" },
  { label: "Mozambique", emoji: "🇲🇿" },
  { label: "Myanmar", emoji: "🇲🇲" },
  { label: "Namibia", emoji: "🇳🇦" },
  { label: "Nauru", emoji: "🇳🇷" },
  { label: "Nepal", emoji: "🇳🇵" },
  { label: "Netherlands", emoji: "🇳🇱" },
  { label: "New Zealand", emoji: "🇳🇿" },
  { label: "Nicaragua", emoji: "🇳🇮" },
  { label: "Niger", emoji: "🇳🇪" },
  { label: "Nigeria", emoji: "🇳🇬" },
  { label: "North Korea", emoji: "🇰🇵" },
  { label: "North Macedonia", emoji: "🇲🇰" },
  { label: "Norway", emoji: "🇳🇴" },
  { label: "Oman", emoji: "🇴🇲" },
  { label: "Pakistan", emoji: "🇵🇰" },
  { label: "Palau", emoji: "🇵🇼" },
  { label: "Panama", emoji: "🇵🇦" },
  { label: "Papua New Guinea", emoji: "🇵🇬" },
  { label: "Paraguay", emoji: "🇵🇾" },
  { label: "Peru", emoji: "🇵🇪" },
  { label: "Philippines", emoji: "🇵🇭" },
  { label: "Poland", emoji: "🇵🇱" },
  { label: "Portugal", emoji: "🇵🇹" },
  { label: "Puerto Rico", emoji: "🇵🇷" },
  { label: "Qatar", emoji: "🇶🇦" },
  { label: "Romania", emoji: "🇷🇴" },
  { label: "Russia", emoji: "🇷🇺" },
  { label: "Rwanda", emoji: "🇷🇼" },
  { label: "Saint Kitts and Nevis", emoji: "🇰🇳" },
  { label: "Saint Lucia", emoji: "🇱🇨" },
  { label: "Saint Vincent and the Grenadines", emoji: "🇻🇨" },
  { label: "Samoa", emoji: "🇼🇸" },
  { label: "San Marino", emoji: "🇸🇲" },
  { label: "Sao Tome and Principe", emoji: "🇸🇹" },
  { label: "Saudi Arabia", emoji: "🇸🇦" },
  { label: "Senegal", emoji: "🇸🇳" },
  { label: "Serbia", emoji: "🇷🇸" },
  { label: "Seychelles", emoji: "🇸🇨" },
  { label: "Sierra Leone", emoji: "🇸🇱" },
  { label: "Singapore", emoji: "🇸🇬" },
  { label: "Slovakia", emoji: "🇸🇰" },
  { label: "Slovenia", emoji: "🇸🇮" },
  { label: "Solomon Islands", emoji: "🇸🇧" },
  { label: "Somalia", emoji: "🇸🇴" },
  { label: "South Africa", emoji: "🇿🇦" },
  { label: "South Korea", emoji: "🇰🇷" },
  { label: "South Sudan", emoji: "🇸🇸" },
  { label: "Spain", emoji: "🇪🇸" },
  { label: "Sri Lanka", emoji: "🇱🇰" },
  { label: "Sudan", emoji: "🇸🇩" },
  { label: "Suriname", emoji: "🇸🇷" },
  { label: "Sweden", emoji: "🇸🇪" },
  { label: "Switzerland", emoji: "🇨🇭" },
  { label: "Syria", emoji: "🇸🇾" },
  { label: "Taiwan", emoji: "🇹🇼" },
  { label: "Tajikistan", emoji: "🇹🇯" },
  { label: "Tanzania", emoji: "🇹🇿" },
  { label: "Thailand", emoji: "🇹🇭" },
  { label: "Timor-Leste", emoji: "🇹🇱" },
  { label: "Togo", emoji: "🇹🇬" },
  { label: "Tonga", emoji: "🇹🇴" },
  { label: "Trinidad and Tobago", emoji: "🇹🇹" },
  { label: "Tunisia", emoji: "🇹🇳" },
  { label: "Turkey", emoji: "🇹🇷" },
  { label: "Turkmenistan", emoji: "🇹🇲" },
  { label: "Tuvalu", emoji: "🇹🇻" },
  { label: "Uganda", emoji: "🇺🇬" },
  { label: "Ukraine", emoji: "🇺🇦" },
  { label: "United Arab Emirates", emoji: "🇦🇪" },
  { label: "United Kingdom", emoji: "🇬🇧" },
  { label: "United States", emoji: "🇺🇸" },
  { label: "Uruguay", emoji: "🇺🇾" },
  { label: "Uzbekistan", emoji: "🇺🇿" },
  { label: "Vanuatu", emoji: "🇻🇺" },
  { label: "Vatican City", emoji: "🇻🇦" },
  { label: "Venezuela", emoji: "🇻🇪" },
  { label: "Vietnam", emoji: "🇻🇳" },
  { label: "Yemen", emoji: "🇾🇪" },
  { label: "Zambia", emoji: "🇿🇲" },
  { label: "Zimbabwe", emoji: "🇿🇼" },
]

export const countriesMap = new Map(countries.map(country => [country.label, country]));