import type { Fundamentals } from '@/types'

export const fundamentals: Fundamentals[] = [
  {
    name: 'Lob',
    sluggedName: 'lob',
    progressionDescription: 'intermediário',
    progressionValue: 50,
    modality: ['futevolei'],
    skillType: ['ataque'],
    description: 'Cabeceio forte com precisão.',
  },
  {
    name: 'Paralela',
    sluggedName: 'paralela',
    progressionDescription: 'intermediário',
    progressionValue: 50,
    modality: ['futevolei'],
    skillType: ['ataque'],
    description: 'Cabeceio forte com precisão.',
  },
  {
    name: 'Diagonal',
    sluggedName: 'diagonal',
    progressionDescription: 'intermediário',
    progressionValue: 50,
    modality: ['futevolei'],
    skillType: ['ataque'],
    description: 'Cabeceio forte com precisão.',
  },
  {
    name: 'Diagonal curta',
    sluggedName: 'diagonal curta',
    progressionDescription: 'intermediário',
    progressionValue: 50,
    modality: ['futevolei'],
    skillType: ['ataque'],
    description: 'Cabeceio forte com precisão.',
  },
  {
    name: 'Pingo',
    sluggedName: 'pingo',
    progressionDescription: 'intermediário',
    progressionValue: 50,
    modality: ['futevolei'],
    skillType: ['ataque'],
    description:
      'Ataque de cabeça, próximo à rede tirando velocidade da bola e deixando-a cair próxima à rede.',
  },
  {
    name: 'Cabeça',
    sluggedName: 'recepcao-passe-de-cabeca',
    progressionDescription: 'intermediário',
    progressionValue: 50,
    modality: ['futevolei', 'altinha'],
    skillType: ['defesa'],
    description: 'Recepção ou levantamento com a cabeça.',
  },
  {
    name: 'Ombro Direito',
    sluggedName: 'ombro-direito',
    progressionDescription: 'intermediário',
    progressionValue: 50,
    modality: ['futevolei', 'altinha'],
    skillType: ['defesa'],
    description: 'Recepção ou levantamento com o ombro direito.',
  },
  {
    name: 'Ombro Esquerdo',
    sluggedName: 'ombro-esquerdo',
    progressionDescription: 'intermediário',
    progressionValue: 50,
    modality: ['futevolei', 'altinha'],
    skillType: ['defesa'],
    description: 'Recepção ou levantamento com o ombro esquerdo.',
  },
  {
    name: 'Peito',
    sluggedName: 'peito',
    progressionDescription: 'intermediário',
    progressionValue: 50,
    modality: ['futevolei', 'altinha'],
    skillType: ['defesa'],
    description: 'Recepção ou levantamento com o peito.',
  },
  {
    name: 'Chapa Direita',
    sluggedName: 'chapa-direita',
    progressionDescription: 'intermediário',
    progressionValue: 50,
    modality: ['futevolei', 'altinha'],
    skillType: ['defesa'],
    description: 'Recepção ou levantamento com a parte interna do pé direito.',
  },
  {
    name: 'Chapa Esquerda',
    sluggedName: 'chapa-esquerda',
    progressionDescription: 'intermediário',
    progressionValue: 50,
    modality: ['futevolei', 'altinha'],
    skillType: ['defesa'],
    description: 'Recepção ou levantamento com a parte interna do pé esquerdo.',
  },
]
