import type { Resources } from '@/types'

export const resources: Resources[] = [
  {
    name: 'Shark Attack',
    sluggedName: 'shark-attack',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['futevolei', 'altinha'],
    skillType: ['attack'],
    description: 'Ataque aéreo acrobático com a parte inferior do pé.',
  },
  {
    name: 'Kamikaze Attack',
    sluggedName: 'kamikaze-attack',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['futevolei', 'altinha'],
    skillType: ['attack'],
    description: 'Ataque aéreo acrobático com a parte superior do pé.',
  },
  {
    name: 'Bicicleta',
    sluggedName: 'bicicleta',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['futevolei', 'altinha'],
    skillType: ['attack'],
    description: 'Ataque aéreo acrobático simulando o ato de pedalar no ar.',
  },
  {
    name: 'Sarrada',
    sluggedName: 'sarrada',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['altinha'],
    skillType: ['attack', 'defense'],
    description: 'Recepção, levantamento ou ataque com o quadril.',
  },
  {
    name: 'Coxa Direita',
    sluggedName: 'coxa-direita',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['futevolei', 'altinha'],
    skillType: ['defense'],
    description: 'Recepção ou levantamento com a coxa direita.',
  },
  {
    name: 'Coxa Esquerda',
    sluggedName: 'coxa-esquerda',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['futevolei', 'altinha'],
    skillType: ['defense'],
    description: 'Recepção ou levantamento com a coxa esquerda.',
  },
  {
    name: 'Cavalo de Troia',
    sluggedName: 'cavalo-de-troia',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['altinha'],
    skillType: ['attack'],
    description: 'Ataque com força e precisão utilizando joelho ou coxa.',
  },
  {
    name: 'Saque com Efeito',
    sluggedName: 'saque-com-efeito',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['futevolei'],
    skillType: ['attack'],
    description:
      'Saque com técnicas que conferem dificuldade na recepção adversária.',
  },
  {
    name: 'Pingo com Finta',
    sluggedName: 'pingo-com-finta',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['futevolei'],
    skillType: ['attack'],
    description:
      'Ataque imprevisível, próximo à rede tirando velocidade da bola e deixando-a cair próxima à rede.',
  },
  {
    name: 'Chilena Direita',
    sluggedName: 'chilena-direita',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['futevolei', 'altinha'],
    skillType: ['defense'],
    description: 'Recepção ou levantamento com parte externa do pé direito.',
  },
  {
    name: 'Chilena Esquerda',
    sluggedName: 'chilena-esquerda',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['futevolei', 'altinha'],
    skillType: ['defense'],
    description: 'Recepção ou levantamento com parte externa do pé esquerdo.',
  },
  {
    name: 'Peito do pé Direito',
    sluggedName: 'peito-do-pe-direito',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['futevolei', 'altinha'],
    skillType: ['defense'],
    description: 'Recepção ou levantamento com parte superior do pé direito.',
  },
  {
    name: 'Peito do pé Esquerdo',
    sluggedName: 'peito-do-pe-esquerdo',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['futevolei', 'altinha'],
    skillType: ['defense'],
    description: 'Recepção ou levantamento com parte superior do pé esquerdo.',
  },
  {
    name: 'Ataque pé Direto',
    sluggedName: 'ataque-pe-direto',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['altinha'],
    skillType: ['attack'],
    description: 'Ataque com precisão e força com o pé direito.',
  },
  {
    name: 'Ataque pé Esquerdo',
    sluggedName: 'ataque-pe-esquerdo',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['altinha'],
    skillType: ['attack'],
    description: 'Ataque com precisão e força com o pé esquerdo.',
  },
  {
    name: 'Levantamento de Letra',
    sluggedName: 'levantamento-de-letra',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['altinha'],
    skillType: ['defense'],
    description: 'Recepção ou levantamento utilizando o pé entrelaçado.',
  },
  {
    name: 'Ataque de Letra',
    sluggedName: 'ataque-de-letra',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['altinha'],
    skillType: ['attack'],
    description: 'Ataque com força e precisão utilizando o pé entrelaçado.',
  },
  {
    name: 'Ataque de Ombro',
    sluggedName: 'ataque-de-ombro',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['altinha'],
    skillType: ['attack'],
    description: 'Ataque com força e precisão com o ombro.',
  },
  {
    name: 'Escorpião',
    sluggedName: 'escorpiao',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['altinha'],
    skillType: ['defense'],
    description: 'Recepção ou levantamento utilizando o calcanhar.',
  },
  {
    name: 'Cola no peito',
    sluggedName: 'cola-no-peito',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['altinha'],
    skillType: ['defense'],
    description: 'Recepção dominando totalmente a bola no peito.',
  },
  {
    name: 'Cola no pé',
    sluggedName: 'cola-no-pe',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['altinha'],
    skillType: ['defense'],
    description: 'Recepção dominando totalmente a bola no pé.',
  },
  {
    name: 'Dois Tempos',
    sluggedName: 'dois-tempos',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['altinha'],
    skillType: ['attack', 'defense'],
    description:
      'Recepção seguida de ataque em apenas dois movimentos rápidos.',
  },
  {
    name: 'Eclipse',
    sluggedName: 'eclipse',
    progressionDescription: 'unfamiliar',
    progressionValue: 0,
    modality: ['altinha'],
    skillType: ['defense'],
    description:
      'Recepção aérea dominando com a parte interna do pé enquanto passa o outro pé pela frente.',
  },
]
